name: Mern stack application

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #gives access to code base
      - uses: actions/setup-node@v3 #does all test and checks for dependencies
        with:
          node-version: 16
      - name: npm install
        run: npm install #install all dependencies
        env:
         CI: true
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -uses: actions/checkout@v3
  #     -uses:
  #      with:
  

  front-end-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: client
